app:
 jwtExpirationMs: 76300000
 jwtSecret: B3n3fr4nc1s
spring:
  application:
    name: hr-user
  datasource:
   url: jdbc:mariadb://localhost:3306/jwt-user?createDatabaseIfNotExist=true
   username: root
   password: root
   driver-class-name: org.mariadb.jdbc.Driver
   hikari:
    connection-timeout: 300000
    maximum-pool-size: 5
    max-lifetime: 180000
    minimum-idle: 200
    validation-timeout: 3000
    idle-timeout: 10000
  jpa:
   open-in-view: false
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   generate-ddl: true
   properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
   show-sql: true
 
